### ISSUE TITLE
fullName without comma breaks frontend

### ISSUE THREAD

**Issue by Eloi-Perez** [chingu-voyages/v42-bears-team-27#130]
**Describe the problem**
On packages\frontend\src\components\dashboard\modals\ClassroomModal\ClassroomModal.tsx
line 100 
                  ```
  <p sx={{ variant: 'text.h4' }}>{`${
                      (authCtx.user as ITeacher).title
                    }.${(authCtx.user as ITeacher).fullName
                      .split(',')[1]
                      .trim()}`}</p>
```
The frontend will break if the name of the teacher doesn't have the structure: string comma string

**To Reproduce**
On creation introduce a fullName without a comma

**Comment by TazDeCoder** [comment]
Eloi can you please handle this since your working on a user story that involves using this component
