### ISSUE TITLE
Create project on repository

### ISSUE THREAD

**Issue by Eloi-Perez** [chingu-voyages/v42-bears-team-27#14]
Tasks:
- [x] Create monorepo with Lerna
- [x] Set up Next.js
- [x] Set up Express.js
- [x] Set up MongoDB Atlas and the connection with the API (Mongoose)

**Comment by TazDeCoder** [comment]
Samad add your backend code from `issue#14` to the branch `chore/setup-repo` under the folder name **packages** - not on the root directory

**Comment by samad13** [comment]
I think you need your branch merged, before I can add my code.

**Comment by TazDeCoder** [comment]
Samad please make these following changes to the backend code:

- Remove package-lock.json file
- Add a **dev** script to your package.json (use nodemon)
- Add a eslint file with airbnb style guide - make to sure to install required deps
- Check that your yarn.lock file is up-to-date

**NOTE: as a team we decided to use yarn not npm so make sure you use that**

If you have any troubles doing this, then please let me know soon or I'll have to do it myself

**Comment by samad13** [comment]
Sorry but am having problem getting the chore/setup-repo branch on my
system.not able to clone it or switched to it.

**Comment by TazDeCoder** [comment]
You need to run the following command:
- `git pull origin`
- `git checkout chore/setup-repo`

Have you tried this?
