### ISSUE TITLE
Teacher classroom creation error

### ISSUE THREAD

**Issue by TazDeCoder** [chingu-voyages/v42-bears-team-27#144]
**Describe the problem**
I'm not able to create a new classroom for a teacher

**Actual behavior**
It throws an error immediately after submitting the new classroom data

**Expected behavior**
I expected it to show me the dashboard with the new classroom data

**To Reproduce**
1. Run dev script on the lastest branch of `dev`
2. Create a new teacher
3. Create a new classroom
4. See an error

**Screenshots**
<img width="960" alt="Screenshot 2023-02-04 141409" src="https://user-images.githubusercontent.com/91470221/216772320-369cc9e6-3e1a-4c70-8b8a-6f798dec3b44.png">

**Additional Information**
It may be an error from the forms, or if not, a backend-related issue

**Comment by Eloi-Perez** [comment]
Hey, @henokkh I think this is what we saw in the call yesterday, could you submit the code that fixes it? thank you
