### ISSUE TITLE
Fail to logout when trying to attempting from teacher navbar

### ISSUE THREAD

**Issue by TazDeCoder** [chingu-voyages/v42-bears-team-27#151]
**Describe the problem**
Logout attempt from teacher navbar doesn't work

**Actual behavior**
When I clicked on the teacher navbar to logout - it didn't work

**Expected behavior**
I expected the screen to redirect me back to the landing page

**To Reproduce**
1. Login as a teacher
2. Click on 'Profile' Icon
3. Press on the 'Logout' item

**Additional Information**
The error you get is to do with the response not being "ok" so perhaps a backend issue? Otherwise, if not, then something wrong with the auth service to logout a user

**Comment by Eloi-Perez** [comment]
@TazDeCoder is this on dev branch already?

**Comment by TazDeCoder** [comment]
@Eloi-Perez I have updated the dev branch with the PR #150 since it was supposed to be merged before hand - so yeah, you should now be able to see the error
