### ISSUE TITLE
Authenticated student login leads to unauthenticated response

### ISSUE THREAD

**Issue by TazDeCoder** [chingu-voyages/v42-bears-team-27#155]
**Describe the problem**
Logging as a student that is valid and with correct credentials leads to unauthenticated response when trying to fetch data

**Actual behavior**
I tried to access the classroom of the authenticated student

**Expected behavior**
I expected the classroom data in which the student belongs to have come back with a response (i.e. data)

**To Reproduce**
1. Login as valid student of a classroom
2. Try to make a request for data of student's classroom
3. See error

**Additional Information**
There must be something wrong with either the cookies sent when logged in, or likely bad authentication for students on that part

**Comment by Eloi-Perez** [comment]
I can't fix it until we have a dashboard, atm is empty on the "dev" branch so I can't make a request from the UI.

**Comment by TazDeCoder** [comment]
Resolved by PR #158
