### ISSUE TITLE
Clean Alert

### ISSUE THREAD

**Issue by Eloi-Perez** [chingu-voyages/v42-bears-team-27#167]
**__Task Description__**
Clean alerts on modals when the modal is closed or in other events if possible

**__Technical Considerations__**
Include any technical considerations including architecture (e.g. API), required libraries, etc.

**__Additional Considerations__**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

**Comment by TazDeCoder** [comment]
I was thinking about that actually the other day and we need to add this sooner or later - do you mind doing this?
