### ISSUE TITLE
Invalid form inputs doesn't prevent form submission

### ISSUE THREAD

**Issue by Eloi-Perez** [chingu-voyages/v42-bears-team-27#174]
**Describe the problem**
Form validators don't prevent the form from being sent

**Henok Comment**
"the validation logic is all there ... I think all we need to do is pass the disabled prop to Button if any of the inputs have any errors"

```
<Button
   sx={{ width: '100%' }}
   type="submit"
   rounded={false}
   icon={<MdSend />}
   disabled={enteredHeadlineHasErrors || enteredMessageHasErrors}
>
   Send Message
</Button>
```
"We should then make sure the Button component accept disabled prop, and is styled differently if disabled "

**Comment by TazDeCoder** [comment]
Can you at least fill in some of the template from the bug? I don't even know what this error is and where it's coming from
