### ISSUE TITLE
Teacher Sign Up

### ISSUE THREAD

**Issue by henokkh** [chingu-voyages/v42-bears-team-27#40]
**User Story Description**
As a teacher
I want to be able to create a teacher’s account in the app
So I can start using the app

**Steps to Follow**
- [x] back-end: create Teacher mongoose model
- [x] back-end: create an endpoint that receives JSON and adds Teacher to the database
- [x] back-end: prevent a single email address from being used to create multiple teachers' accounts
- [x] back-end: add validation of received JSON data
- [x] front-end: create teacher sign-up form (markup)
- [x] front-end: add request sending logic
- [x] front-end: add logic to handle the server's response
- [x] front-end: style based on Figma design

**Additional Considerations**

**Comment by Eloi-Perez** [comment]
Passport.js is not used to hash passwords. 
Look at my commented code for the hashing on 

https://github.com/chingu-voyages/v42-bears-team-27/blob/feature/create-students/packages/backend/models/studentModel.js
And the commented line here, to access the hashing function.

https://github.com/chingu-voyages/v42-bears-team-27/blob/feature/create-students/packages/backend/controllers/studentControllers.js

(is just commented temporarily, it might not be if you check this after me pushing more commits)
