### ISSUE TITLE
Add UI components

### ISSUE THREAD

**Issue by TazDeCoder** [chingu-voyages/v42-bears-team-27#51]
These are the UI components that are to be used throughout the development of the frontend UI; for instance, when you need to use a button component you would import that component from that folder

Components:
- [x] Button
- [x] TextField
- [x] Calendar
- [x] IconButton
- [x] Modal

**Comment by Eloi-Perez** [comment]
Maybe you already have an idea for the modal, but if not, I've used this library recently and I think is really good @radix-ui/react-dialog

**Comment by TazDeCoder** [comment]
I'll have a look at this library myself and use it for the Modal component IF it is reasonable and a good idea to
